//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateFinancialPaymentPlan.OdysseyAPIServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tylertech.com/", ConfigurationName="OdysseyAPIServiceReference.APIWebServiceSoap")]
    public interface APIWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyTxnExecution", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyTxnExecution(string odysseyTransactionXML, string siteKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyTxnExecutionRollback", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyTxnExecutionRollback(string odysseyTransactionXML, string siteKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyTxnExecutionAllowFaults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyTxnExecutionAllowFaults(string odysseyTransactionXML, string siteKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyTxnExecutionRollbackAllowFaults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyTxnExecutionRollbackAllowFaults(string odysseyTransactionXML, string siteKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyTxnExecutionWithRetry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyTxnExecutionWithRetry(string odysseyTransactionXML, string siteKey, int retryCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyTxnExecutionRollbackWithRetry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyTxnExecutionRollbackWithRetry(string odysseyTransactionXML, string siteKey, int retryCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyTxnExecutionWithRetryAllowFaults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyTxnExecutionWithRetryAllowFaults(string odysseyTransactionXML, string siteKey, int retryCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyTxnExecutionRollbackWithRetryAllowFaults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyTxnExecutionRollbackWithRetryAllowFaults(string odysseyTransactionXML, string siteKey, int retryCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyMsgExecution", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyMsgExecution(string odysseyMessageXML, string siteKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tylertech.com/OdysseyMsgExecutionAllowFaults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OdysseyMsgExecutionAllowFaults(string odysseyMessageXML, string siteKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIWebServiceSoapChannel : UpdateFinancialPaymentPlan.OdysseyAPIServiceReference.APIWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIWebServiceSoapClient : System.ServiceModel.ClientBase<UpdateFinancialPaymentPlan.OdysseyAPIServiceReference.APIWebServiceSoap>, UpdateFinancialPaymentPlan.OdysseyAPIServiceReference.APIWebServiceSoap {
        
        public APIWebServiceSoapClient() {
        }
        
        public APIWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string OdysseyTxnExecution(string odysseyTransactionXML, string siteKey) {
            return base.Channel.OdysseyTxnExecution(odysseyTransactionXML, siteKey);
        }
        
        public string OdysseyTxnExecutionRollback(string odysseyTransactionXML, string siteKey) {
            return base.Channel.OdysseyTxnExecutionRollback(odysseyTransactionXML, siteKey);
        }
        
        public string OdysseyTxnExecutionAllowFaults(string odysseyTransactionXML, string siteKey) {
            return base.Channel.OdysseyTxnExecutionAllowFaults(odysseyTransactionXML, siteKey);
        }
        
        public string OdysseyTxnExecutionRollbackAllowFaults(string odysseyTransactionXML, string siteKey) {
            return base.Channel.OdysseyTxnExecutionRollbackAllowFaults(odysseyTransactionXML, siteKey);
        }
        
        public string OdysseyTxnExecutionWithRetry(string odysseyTransactionXML, string siteKey, int retryCount) {
            return base.Channel.OdysseyTxnExecutionWithRetry(odysseyTransactionXML, siteKey, retryCount);
        }
        
        public string OdysseyTxnExecutionRollbackWithRetry(string odysseyTransactionXML, string siteKey, int retryCount) {
            return base.Channel.OdysseyTxnExecutionRollbackWithRetry(odysseyTransactionXML, siteKey, retryCount);
        }
        
        public string OdysseyTxnExecutionWithRetryAllowFaults(string odysseyTransactionXML, string siteKey, int retryCount) {
            return base.Channel.OdysseyTxnExecutionWithRetryAllowFaults(odysseyTransactionXML, siteKey, retryCount);
        }
        
        public string OdysseyTxnExecutionRollbackWithRetryAllowFaults(string odysseyTransactionXML, string siteKey, int retryCount) {
            return base.Channel.OdysseyTxnExecutionRollbackWithRetryAllowFaults(odysseyTransactionXML, siteKey, retryCount);
        }
        
        public string OdysseyMsgExecution(string odysseyMessageXML, string siteKey) {
            return base.Channel.OdysseyMsgExecution(odysseyMessageXML, siteKey);
        }
        
        public string OdysseyMsgExecutionAllowFaults(string odysseyMessageXML, string siteKey) {
            return base.Channel.OdysseyMsgExecutionAllowFaults(odysseyMessageXML, siteKey);
        }
    }
}
